// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/base_dna_version.test.ts.

/** The version of the `@tssuite/base-dna` package. */
export const baseDnaVersion = '1.1.1';
