// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/dna_base_version.test.ts.

/** The version of the `@tssuite/dna-base` package. */
export const dnaBaseVersion = '0.0.1';
